#!/bin/bash
$searchPath
echo "1. Decide Condition"
if [ $# -lt 1 ] 
then 
	export CSCOPE_DB=$PWD/cscope.out
	searchPath=.
else
	searchPath=$@
fi

echo "2. File Operation"
rm -rf cscope.*
touch cscope.files

echo "3. Get Filelist"
for x in $searchPath
do
	find $x -name "*.h" -o -name "*.xml"  -o -name "*.rc" -o -name "*.hpp" -o -name "*.cc"  -o -name "*.c" -o -name "*.mk" -o -name "*.cpp" -o -name "*.java" -o -name "*.xml" -o -name "*.C" >> cscope.files
done

echo "4. Edit Filelist"
sed "s#^#$PWD/#g" -i cscope.files
sed '/test/d' -i cscope.files
sed '/Test/d' -i cscope.files
sed '/mock/d' -i cscope.files
sed '/Mock/d' -i cscope.files

echo "5. Generate the cscope-related file"
cscope -bkq -i cscope.files > /dev/null 2>&1

echo "6. Generate the ctag-related file"
#/home/rock/github/RockLinux/ctags -h cpp cc c C h hpp java -R --fields=+IS $searchPath > /dev/null 2>&1
ctags --exclude=*.js -h .cpp.cc.c.C.h.hpp.java -R $@ > /dev/null 2>&1

echo "7. Export Environment"
export CSCOPE_DB=$PWD/cscope.out

echo "8. END!!"
